#!/usr/bin/env ruby
require "client"

Server = 'localhost'

Options = <<EOS
OPTIONS:
  drink user amount
  clean user amount
  table
  status user
  password
EOS

if ARGV.size == 0
  exit
end

client = JeneverClient.new(Server,2625)
begin
  client.__send__(ARGV.shift.to_sym,*ARGV)
rescue NoMethodError,ArgumentError
  puts "usage: #{$0} [OPTIONS]"
  puts Options
end